import type { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '../сomponents/Header'
import { MainLayout } from '../сomponents/MainLayout'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RJournal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet" />
      </Head>

      <Header />
      <MainLayout/>
   </div>
  )
}

export default Home
